---
title: "Constitutions"
output:
  pdf_document: default
  html_document: default
date: "2022-10-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)
library(dplyr)
library(infer)

```

```{r}
constitution <- read_csv("ccpcnc_v4_small.csv")
```


```{r}
constitution <- constitution |>
  drop_na(em) |>
  select(country:evnttype, em:emother_98) |>
  filter(year > "1988")
```

```{r}
liberal <- read_csv("V-Dem.csv")
```

```{r}
liberal <- liberal |>
  select(country_name, year, v2x_libdem, v2mecenefm, 
         v2mecenefi, v2mecrit, v2mebias) |>
  filter(year > "1988")
```

Finding differences in country names to prevent errors in `inner_join`
```{r}
#unique(liberal$country_name)
#unique(constitution$country)
```

```{r}
liberal <- liberal |>
  rename(country = country_name)
```

##Filtering out duplicate data in constitution
```{r}
##This filters out all Serbia data, why isn't the "and" function (&) not working
constitution <- constitution |>
  filter(country != "Serbia" & year != "2006")  

```

##Left Join
```{r}
joined <- constitution |>
  left_join(liberal) |>
  select(country, year, v2x_libdem, em, emdecl, emappr_1, emappr_2) 
```

##Summarizing variables

```{r}
joined <- joined |>
  mutate(emdecl = case_when(
    emdecl == 1 ~ "Head of State",
    emdecl == 2 ~ "Head of Government",
    emdecl == 3 ~ "Head of State or Head of Gov",
    emdecl == 4 ~ "Gov/Cabinet",
    emdecl == 5 ~ "1st Legislative Chamber",
    emdecl == 6 ~ "2nd Legislative Chamber",
    emdecl == 7 ~ "Both Chambers",
    emdecl == 90 ~ "Left to law",
    emdecl == 96 ~ "Other",
    emdecl == 97 ~ "Unknown",
    emdecl == 98 ~ "Not Specified",
    emdecl == 99 ~ "Not Applicable"
  ))

```
```{r}
target_data <- joined |>
  group_by(emdecl) |>
  summarize(mean_liberal = mean(v2x_libdem, na.rm = TRUE)) #|>
  #pivot_wider(names_from = emdecl, values_from = mean_liberal)  
target_data
```


Bar Plot
```{r}
target_data |>
  ggplot(aes(x = emdecl,  y = mean_liberal)) +
  geom_bar(stat = "identity") +
  scale_x_discrete(guide = guide_axis(n.dodge=2)) +
  labs(x = "Who Declares State of Emergencies",
       y = "V-Dem Liberal Democracy Index")
  

  
```
```{r}
joined <- joined |>
  mutate(em = case_when(
    em == 1 ~ "Provision",
    em == 2 ~ "No Provision",
    em == 96 ~ "Other",
    em == 97 ~ "unknown")
      )
target_data2 <- joined |>
  group_by(em) |>
  summarize(mean_liberal = mean(v2x_libdem, na.rm = TRUE)) |>
  filter(!row_number() %in% (2))
target_data2
```

```{r}
target_data2 |>
  ggplot(aes(x = em, y = mean_liberal)) +
  geom_bar(stat = "identity") +
  labs(x = "Provision on Calling a State of Emergency in the Constitution", 
       y = "V-Dem Liberal Democracy Index",
       title = "Effect of Having a Provision About State of Emergencies on Liberal Democracy")
```


  

