---
title: "Gov 50 Final Project"
author: "Larson Avery"
description: "Identifying demographic trends and variables that lead polls astray"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

Milestone 1:
I want to dive into data from a recent federal election, probably related to  House of Representatives races and compare polls leading up to the election with the actual results. I want to combine US Census data with polling to create a large dataset of demographic, economic, or geographic variables. Then I want to investigate if trends in these variables make polls accurate or inaccurate at predicting election outcomes.

Milestone 2:
Research Question: How did percentage of workers in the manufacturing sector, unemployment, and percent of households making under $15,000 a year affect the accuracy of polls in the 2016 Presidential election? Polls put Hillary Clinton ahead of Donald Trump and while he did not win the popular vote, he did win far more votes than expected due to the undercounting of voters. I want to explore how variables such as rural poverty, loss of manufacturing jobs, and unemployment—issues Trump emphasized—affected how accurate polls were for the 2016 Presidential Election. I hypothesize states with a higher manufacturing share, higher unemployment, and high proportions of poor households increases discrepancies between predicted and actual vote shares in FiveThirtyEight’s model. The explanatory variables are from a table on the US Census website that measure a variety of different economic variables. These are extremely recent and accurate as the Census reaches the vast majority of the US population. The outcome variable is the predicted popular vote for Trump by FiveThirtyEight (measured by aggregating many polls together) minus the final results of the popular vote by state. Each variable will be measured separately. A positive relationship between the variables and poll error with low standard deviation will support my hypothesis whereas a weak relationship or opposite relationship will disprove my hypothesis. 

Unfortunately at this time I have been unable to find FiveThirtyEight’s predicted popular vote share for 2016. I have found this dataset for 2020 on GitHub but a study of those results would be far less interesting as pollsters probably adjusted to polling for Trump between 2016 and 2020.



Demographic data: https://data.census.gov/cedsci/table?q=employment%20statistics&g=0100000US,%240400000&tid=ACSDP1Y2021.DP03&moe=false&tp=true

Election Polls: *need to find 2016 version
https://github.com/fivethirtyeight/data/tree/master/election-forecasts-2020 ->
https://projects.fivethirtyeight.com/2020-general-data/presidential_poll_averages_2020.csv

Election Results:
https://www.fec.gov/resources/cms-content/documents/federalelections2016.pdf
